### ISSUE TITLE
EventLoopFinisher not added

### ISSUE THREAD

**Issue by songziming** [mgsxx/QEverCloud#5]
I'm using QEverCloud by including it's source code as a subdir project in my project tree. When I link to this library, Qt reports "unresolved reference to vtable for EventLoopFinisher" (or something like that).

I found EventLoopFinisher.{h,cpp} are in the source directory, but bot included in the `.pro` file. After I added them in the QEverCloud.pro file, the problem was solved.

By the way, I would appreaciate if you can split the source without example and other file as a single repo. So that I can include that project as a git module in my project.

**Comment by mgsxx** [comment]
Hi!. Thans for the interest in QEverCloud.

Unfortunately, I can't help you.
1. I have lost interest in Evernote. It's a doomed project IMHO; anyway they develop in the direction I disagree completely.
2. I have migrated from Windows and C++/Qt to Mac and Swift. It's so much cooler there that I have no intention to return.

So I do not have much time nor interest in developing QEverCloud. I suggest you to fork the project and maintain it as you see fit.

By the way, I have never released the code that I used to generate the QEverCloud from Thrift files. If you interested I can upload it in a separate repo. It will be needed if Evernote will ad new API to regenerate sources. The sources are kind of a mess and have no comments, but still. If you are interested I'll release them.

**Comment by songziming** [comment]
I did notice those generated code are not from evernote-cpp-sdk, and yes I want to see the code.

But I won't fork it right now. I have to study the code first and understand how it's working.

**Comment by mgsxx** [comment]
Do as you will.

The code being not from evernote-cpp-sdk is the whole point of QEverCloud.

I will post the generator code in a few days. I do not promise it will build right off the bat.
The code consist of several subrpojects, some of them using compiled subrpojects in its own build process.
I automated the build chain with non-trivial qmake tinkering which I have no time to explain.

Sorry, but you on your own. Alas, I just have no time now for QEverCloud.

**Comment by d1vanov** [comment]
Hi, 

I am as well interested in QEverCloud as well as the sources for the translator from Evernote Thrift files. In my (currently private) project I have added the support of QWebEngine to QEverCloud (for oauth, instead of QtWebKit) which I would be pleased to contribute. 

Thanks @mgsxx for your work on QEverCloud so far!

**Comment by mgsxx** [comment]
Thanks! I'm glad someone have found QEverCloud useful :)
I myself ended up using it mostly to migrate my data out of Evernote...

Guys, I really do think that somebody who is really interested in Evernote + Qt should maintain the work further. I will upload the generator sources in a few days, I promise. I propose someone from you take it from there. Maybe I will find time to answer to some questions about the generator, but that I do not promise. I have another projects with deadlines and my horribly neglected family to boot. And I have practically abandoned Evernote, Windows, Qt, C++ in favour of Mac, iOS and Swift. It would be great to develop QEverCloud further but I can't be everywhere.

So fork it, tinker it, modernize it. You have my blessing. But I myself have not plans to maintain the project.

If someone of you who use QEverCloud are willing to do the work I will include links to your forks on the main page.

**Comment by d1vanov** [comment]
Point taken :) 

As long as my project still depends on QEverCloud, I'd definitely maintain it myself and as long as the "official" version is no longer actively maintained, think I'll just update my already existing fork of QEverCloud here on GitHub with the recent developments I did. 

Thanks again for all the time and efforts you devoted to this project.

**Comment by mgsxx** [comment]
If you want I will add a link to your fork on my QEverCloud main page as a place to look for the more recent version, so people will find your work  and use it instead. Your aouth implementation alone is interesting.

**Comment by d1vanov** [comment]
I'll need some time to properly update the contents of my fork, a few days maybe. Then it would perhaps make sense to add a link to it. I'll comment here when I'm ready on my side. 

> Your aouth implementation alone is interesting
It's nothing fancy really, not like another implementation but more like fixing API breaks within the existing implementation. E.g. with QWebEngine we no longer have QWebView but have QWebEngineView instead and so on.

**Comment by mgsxx** [comment]
Ok, I’ll wait for you to get ready.

I, again, promise to upload the generator sources. Someday you’ll need them if you continue to maintain the project.

“fixing API breaks” and moderizing it with QWebEngineView - maybe it’s nothing fancy but that’s the difference between an alive and maintained project and a dead one.

**Comment by d1vanov** [comment]
Ok, I have updated my fork now. The only immediate thing left to do is to create my own doc page, I'll get to it eventually. 

Beyond other changes I have also included EventLoopFinisher.h/.cpp to the library.

**Comment by mgsxx** [comment]
I have uploaded the generator sources. See [QEverCloudGenerator ](https://github.com/mgsxx/QEverCloudGenerator)

And I have added the link to your fork in my QEverCloud readme.

**Comment by d1vanov** [comment]
Thanks a lot!
I've just checked out your blog articles about qmake. Just wow. I mostly use CMake for my own projects but even though I never saw anything of that level of detail and depth on qmake as your blog articles. Much appreciation for taking the time to write down that material as well as for the generator sources.

**Comment by mgsxx** [comment]
You’re welcome!
